lib/protocols/weather6.js
src/protocols/weather6.coffee

Finally we have minus degrees out there and I was able to find the correct start for the temperature bit.

Minus temperatures for weather6 protocol

---

src/controller.coffee
src/protocols/contact2.coffee
test/lib-controller.coffee

those door contact only emits  when the magnet move in front of the sensor

New protocol : contact2, can be used for cheap door contact 

---

lib/protocols/switch4.js
src/protocols/switch4.coffee

https://github.com/pimatic/pimatic/issues/476

correct the pulse length for protocol switch4. 

---

lib/controller.js
lib/protocols/switch10.js
src/controller.coffee
src/protocols/switch10.coffee

When sending the message is one bit longer than the received one, but it
works.
Original: 110001111001011110001111001101001101110101010110101100011
Send: 1100011110010111100011110011010011011101010110110101100011
Could not test the groupfeature because I only have simple wallswitches
without "all on/off" button.
The unit seems to be the same on all switches.

Added home easy advanced

---

lib/controller.js
lib/protocols/alarm1.js
src/controller.coffee
src/protocols/alarm1.coffee

When you switch the device on or off it will alert for about 5 seconds.
At the moment it is not possible that it stays on, because we need a new device definiton in pimatic.

Added support for FA20RF smokedetectors

---

lib/controller.js
lib/protocols/pir3.js
src/controller.coffee
src/protocols/pir3.coffee

The unit id ist still ugly but it should work.

added support for Elro DB286A doorbell

---

lib/controller.js
lib/protocols/awning1.js
lib/protocols/shutter1.js
src/controller.coffee
src/protocols/awning1.coffee
src/protocols/shutter1.coffee

2 new protocols which only differ in the pulse length. One is for a rolling (Nobily) and the other is for a noname awning. Both types are "command".
commands for awning1: out, stop, in
commands for rolling2: up and down
both: id
If you find somewhere a commit called "Test Upload", please ignore and delete it :-)

Pull request for 2 new protocols

---

src/protocols/switch18.coffe
src/protocols/weather8.coffee

Hello
Following our discussion on the forum. I added these two files to the protocol list.
Hope it will help.
Temperature sensor is one of the cheap sensor we can find : LIDL or Carrefour in France.
The Switch is the Otio (Enexo - 750042 / ret-8003)
I tried to reverse the protocol, and try to improve it soon.
Thanks
Emmanuel

New Protocols : Temperature / Humidity sensor & Otio Switch

---

lib/controller.js
lib/protocols/awning1.js
lib/protocols/contact3.js
lib/protocols/shutter1.js
lib/protocols/switch19.js
src/controller.coffee
src/protocols/awning1.coffee
src/protocols/contact3.coffee
src/protocols/shutter1.coffee
src/protocols/switch19.coffee

shutter1: again a command due to having a stop button
contact3: for a Home Easy HE852 which emits a signal on open and close

Changes in awning1 and shutter1, new contact3 for Home Easy HE852

---

lib/controller.js
lib/protocols/alarm2.js
lib/protocols/awning2.js
lib/protocols/shutter3.js
lib/protocols/shutter4.js
lib/protocols/weather10.js
src/controller.coffee
src/protocols/alarm2.coffee
src/protocols/awning2.coffee
src/protocols/shutter3.coffee
src/protocols/shutter4.coffee
src/protocols/weather10.coffee

alarm2: http://forum.pimatic.org/topic/548/solved-fa21rf-smoke-detector-alarm2
awning2: http://forum.pimatic.org/topic/534/awning2-protocol
shutter3: http://forum.pimatic.org/topic/525/solved-nice-shutter-device-with-hand-switch-option-but-wihtout-protocol-shutter3
shutter4: http://forum.pimatic.org/topic/541/solved-remote-shutters-rohrmotor24-shutter4
weather10: http://forum.pimatic.org/topic/476/solved-velleman-ws8426s-temp-sensor-weather10

add alarm2, awning2, shutter3, shutter4, weather10

---

lib/controller.js
lib/helper.js
lib/protocols/generic2.js
src/controller.coffee
src/helper.coffee
src/protocols/generic2.coffee
test/lib-controller.coffee

Designing a new protocol for ATTiny45 based generic sensor node.

Changes to include generic2 protocol for sensor node communications.

---

src/helper.coffee
src/protocols/generic2.coffee
test/lib-controller.coffee

Yikes @Icesory , there was a bug in my checksum computation. Nice catch! Fixed it and added a test to verify the fix.

Fixing bug in checksum computation, adding a test to verify fix.

---

src/controller.coffee
src/protocols/doorbell3.coffee
test/lib-controller.coffee

WP515S doorbell (smart-home.com.hk/docs/product_pdf/WP515S.pdf) protocoll added as doorbell3.
doorbell has 16 position switch aka house code (" to avoid interference"), and a 8 position unit code.
pos=>id
01=>0 0000
02=>C 1100
03=>4 0100
04=>F 1111
05=>7 0111
06=>B 1011
07=>3 0011
08=>A 1010
09=>2 0010
10=>E 1110
11=>6 0110
12=>D 1101
13=>5 0101
14=>9 1001
15=>1 0001
16=>8 1000

Added protocol doorbell3 for WP515S doorbell.

---

lib/protocols/switch1.js

Fixes https://github.com/pimatic/pimatic/issues/857

Change binary to number

---

lib/controller.js
lib/protocols/switch27.js
src/controller.coffee
src/protocols/switch27.coffee
test/lib-controller.coffee

switch27 since I have pull requests for switch25 and 26 already.

add new switch27 for Chacon ZEN

---

lib/controller.js
lib/protocols/switch26.js
src/controller.coffee
src/protocols/switch26.coffee
test/lib-controller.coffee

named it 26 since I made another pull request for switch25.

add switch26 (Chacon EMW200TC)

---

src/controller.coffee
src/protocols/rawswitch.coffee

Created a raw switch to replay pulses

Added a raw switch

---

src/protocols/doorbell3.coffee
test/lib-controller.coffee

updated test sequence for doorbell 3

update doorbell3 coffee and test

---

src/protocols/rawshutter.coffee

Created a RAW shutter to support shutters whose protocols are not yet implemented in rfcontroljs.

A RAW shutter

---

lib/protocols/switch31.js
src/controller.coffee
src/protocols/switch31.coffee
test/lib-controller.coffee

Protocol for Masterplug UK wall sockets

Add Switch31 protocol
